### ISSUE TITLE
UnboundLocalError: local variable 'DOA_batch_pred_cart' referenced before assignment

### ISSUE THREAD

**Issue by Luosuu** [DavidDiazGuerra/Cross3D#1]
I installed all the requirement dependencies and run
```
python3 1sourceTracking_Cross3D.py
```
but I got the error message as 
```
Training network...

Epoch 1/80:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "1sourceTracking_Cross3D.py", line 93, in <module>
    learner.train_epoch(dataset_train, trajectories_per_batch, trajectories_per_gpu_call, lr=lr, epoch=epoch_idx)
  File "xxx/Cross3D/acousticTrackingLearners.py", line 92, in train_epoch
    del DOA_batch_pred_cart, loss
UnboundLocalError: local variable 'DOA_batch_pred_cart' referenced before assignment

```

**Comment by Luosuu** [comment]
I downloaded the LibriSpeech database but I didn't configure the path properly.
the path was confusing
```
LibriSpeech/train-clean-100/LibriSpeech/train-clean-100
```
